CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS CATEGORIES CASCADE;
CREATE TABLE CATEGORIES (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(60) NOT NULL
);

DROP TABLE IF EXISTS ENDORSEMENTS CASCADE;
CREATE TABLE ENDORSEMENTS (
  UUID UUID NOT NULL PRIMARY KEY,
  GRANTER_USERNAME VARCHAR(40) NOT NULL,
  RECEIVER_USERNAME VARCHAR(40) NOT NULL,
  SCORE INT NOT NULL,
  REASON VARCHAR(500),
  URL VARCHAR(300),
  CREATED DATE DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS ENDORSEMENT_LIKES CASCADE;
CREATE TABLE ENDORSEMENT_LIKES (
  UUID UUID NOT NULL PRIMARY KEY,
  GRANTER_USERNAME VARCHAR(40) NOT NULL,
  ENDORSEMENT_UUID UUID NOT NULL,
  REASON VARCHAR(500),
  CREATED DATE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_ENDORSEMENT_LIKES_ENDORSEMENTS FOREIGN KEY (ENDORSEMENT_UUID) REFERENCES ENDORSEMENTS(UUID)
);

DROP TABLE IF EXISTS CATEGORY_ASSIGNMENTS CASCADE;
CREATE TABLE CATEGORY_ASSIGNMENTS (
  ENDORSEMENT_UUID UUID NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  CONSTRAINT FK_CATEGORY_ASSIGNMENTS_ENDORSEMENTS FOREIGN KEY (ENDORSEMENT_UUID) REFERENCES ENDORSEMENTS(UUID),
  CONSTRAINT FK_CATEGORY_ASSIGNMENTS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
  CONSTRAINT PK_ENDORSEMENT_CATEGORY PRIMARY KEY (ENDORSEMENT_UUID, CATEGORY_ID)
);